# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5b4b54b1b0c805bbf53fd7897c330a710e7934d47b9828a747a959f523b8bc4c43df4bc61e692ce00b58da255199feecf3b6f44f592467d8a54376184cef7053

test:
  secret_key_base: 178814113c7829bae86000fb69ead6fe66b566f41b7f1ba17294b5e1dfd31c18cedd43a26d50eefe5080fceddd571a611e80279b7b518fbd2cb1c6138f800616

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
